function emit()
  return BPF.emit({
    BPF.STX_MEM(BPF.DW, BPF.R10, BPF.R1, -8),
    BPF.STX_MEM(BPF.DW, BPF.R10, BPF.R2, -16),
    BPF.STX_MEM(BPF.DW, BPF.R10, BPF.R3, -24),
    BPF.STX_MEM(BPF.DW, BPF.R10, BPF.R4, -32),
    BPF.STX_MEM(BPF.DW, BPF.R10, BPF.R5, -40),
    BPF.STX_MEM(BPF.DW, BPF.R10, BPF.R6, -48),
    BPF.STX_MEM(BPF.DW, BPF.R10, BPF.R7, -56),
    BPF.STX_MEM(BPF.DW, BPF.R10, BPF.R8, -64),
    BPF.STX_MEM(BPF.DW, BPF.R10, BPF.R9, -72)
  })
end
