on: [push]

jobs:
  build:
    name: Run build test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2
    - name: Build static binary with Docker
      run: |
        sudo ./scripts/build_static.sh
