name: Build for every push to master

on:
  push:
    branches:
      - master

jobs:
  build_and_publish_ipftrace2_builder:
    name: Build and push ipftrace2-builder image
    runs-on: ubuntu-latest
    env:
      USER_NAME: yutarohayakawa
      IMAGE_NAME: ipftrace2-builder
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ env.USER_NAME }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          cache-from: type=registry,ref=ghcr.io/${{ env.USER_NAME }}/${{ env.IMAGE_NAME }}:latest
          cache-to: type=inline
          tags: |
            ghcr.io/${{ env.USER_NAME }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
            ghcr.io/${{ env.USER_NAME }}/${{ env.IMAGE_NAME }}:latest
