on:
  release:
    types: [created]

jobs:
  generate:
    name: Create latest binary
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2
    - name: Build static binary with Docker
      run: |
        sudo ./scripts/build_static.sh
        tar cfvz ipftrace2_amd64.tar.gz ipft
    - name: Publish binary
      uses: skx/github-action-publish-binaries@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        args: "ipftrace2_amd64.tar.gz"
