name: Release build

on:
  release:
    types: [created]

jobs:
  build_and_publish_all:
    name: Build and push ipftrace2-builder image
    runs-on: ubuntu-latest
    env:
      USER_NAME: yutarohayakawa
      IMAGE_NAME: ipftrace2-builder
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ env.USER_NAME }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          cache-from: type=registry,ref=ghcr.io/${{ env.USER_NAME }}/${{ env.IMAGE_NAME }}:latest
          cache-to: type=inline
          tags: |
            ghcr.io/${{ env.USER_NAME }}/${{ env.IMAGE_NAME }}:${{ github.ref_name }}

      - name: Build static binary with Docker
        run: |
          sudo ./scripts/build_static.sh
          tar cfvz ipftrace2_amd64.tar.gz ipft

      - name: Publish binary
        uses: skx/github-action-publish-binaries@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: "ipftrace2_amd64.tar.gz"
