name: Smoke Test

on:
  push:
    branches:
    - master
  pull_request:
  schedule:
  - cron: '0 6 * * 5'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Build builder image
      run: sudo docker build -t ipft-builder:latest .

    - name: Build ipft binary with builder
      run: DOCKER_IMAGE=ipft-builder VERSION=latest sudo -E ./scripts/make.sh

    - name: Save builder image
      run: sudo docker image save ipft-builder > ipft-builder.tar

    - name: Upload builder image for later use
      uses: actions/upload-artifact@v4
      with:
        name: ipft-builder.tar
        path: ipft-builder.tar

    - name: Upload ipft binary for later use
      uses: actions/upload-artifact@v4
      with:
        name: ipft
        path: src/ipft

  check_format:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Download builder image
      uses: actions/download-artifact@v4
      with:
        name: ipft-builder.tar

    - name: Import builder image
      run: sudo docker image load -i ipft-builder.tar

    - name: Run format check
      run: |
        DOCKER_IMAGE=ipft-builder VERSION=latest sudo -E ./scripts/make.sh format
        ./scripts/format.sh check_diff

  check_docs:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Download ipft binary
      uses: actions/download-artifact@v4
      with:
        name: ipft
        path: src/ipft

    - name: Set ipft permission
      run: chmod 755 src/ipft

    - name: Check docs
      run: ./scripts/docs.sh check_diff

  run_with_minimum_kernel:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Download ipft binary
      uses: actions/download-artifact@v4
      with:
        name: ipft

    - name: Run smoke test on LVH VM
      uses: cilium/little-vm-helper@a4311c6d054de3008bdf9195b0fabf6ee60d8bdd # v0.0.17
      with:
        test-name: min-kernel
        image: complexity-test
        image-version: rhel8-20240305.092417
        cpu: 4
        mem: 4G
        host-mount: ./
        install-dependencies: 'true'
        cmd: |
          uname -a
          # TODO: Create our own image to get rid of this
          apt-get update
          apt-get install -y netcat-traditional jq
          cd /host
          chmod +x ./ipft
          IPFT=./ipft ./tests/smoke-test.sh function

  run_with_maximum_kernel:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Download ipft binary
      uses: actions/download-artifact@v4
      with:
        name: ipft

    - name: Run smoke test on LVH VM
      uses: cilium/little-vm-helper@a4311c6d054de3008bdf9195b0fabf6ee60d8bdd # v0.0.17
      with:
        test-name: max-kernel
        image: complexity-test
        image-version: bpf-next-20240315.012542
        cpu: 4
        mem: 4G
        host-mount: ./
        install-dependencies: 'true'
        cmd: |
          uname -a
          # TODO: Create our own image to get rid of this
          apt-get update
          apt-get install -y netcat-traditional jq
          cd /host
          chmod +x ./ipft
          IPFT=./ipft ./tests/smoke-test.sh function function_graph
