name: Smoke Test

on:
  push:
    branches:
    - master
  pull_request:

jobs:
  build_binary:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build ipft binary with Docker
      run: |
        VERSION=latest sudo -E ./scripts/make.sh

    - name: Upload ipft binary for later use
      uses: actions/upload-artifact@v3
      with:
        name: ipft
        path: src/ipft

  run_with_minimum_kernel:
    runs-on: macos-10.15
    needs: build_binary
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Download ipft binary
      uses: actions/download-artifact@v3
      with:
        name: ipft

    - name: Boot CentOS Stream 8
      run: |
        cp ./tests/Vagrantfile.centos-stream8 ./Vagrantfile
        vagrant up

    - name: Display kernel version
      run: vagrant ssh -- "/bin/sh -c 'uname -a'"

    - name: Move ipft binary to executable path
      run: vagrant ssh -- "/bin/sh -c 'cd /vagrant && chmod +x ipft && sudo mv ipft /usr/bin'"

    - name: Install required packages
      run: vagrant ssh -- "/bin/sh -c 'sudo dnf -y install jq nc'"

    - name: Run smoke test
      timeout-minutes: 5
      run: vagrant ssh -- "/bin/sh -c 'cd /vagrant && sudo ./tests/smoke-test.sh function'"

  run_with_maximum_kernel:
    runs-on: macos-10.15
    needs: build_binary
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Download ipft binary
      uses: actions/download-artifact@v3
      with:
        name: ipft

    - name: Boot Arch Linux
      run: |
        cp ./tests/Vagrantfile.archlinux-latest ./Vagrantfile
        vagrant up

    - name: Display kernel version
      run: vagrant ssh -- "/bin/sh -c 'uname -a'"

    - name: Move ipft binary to executable path
      run: vagrant ssh -- "/bin/sh -c 'cd /vagrant && chmod +x ipft && sudo mv ipft /usr/bin'"

    - name: Install required packages
      run: |
        vagrant ssh -- "/bin/sh -c 'yes | sudo pacman -S jq gnu-netcat'"

    - name: Run smoke test
      timeout-minutes: 20  # function_graph tracing takes time for detaching
      run: |
        vagrant ssh -- "/bin/sh -c 'cd /vagrant && sudo ./tests/smoke-test.sh function function_graph'"
